name: 'Set auto merge'
'on':
  workflow_call:
    secrets:
      access-token:
        required: true

jobs:
  set-auto-merge:
    runs-on: ubuntu-latest
    #if: ${{ github.event.review.state == 'APPROVED' && github.event.review.pull_request.user.login == 'zregvart' }} #dependabot[bot]
    steps:
      - run: gh pr merge ${{ github.event.pull_request.url }} --auto
        env:
          GH_REPO: ${{ github.event.repository.full_name }}
          GITHUB_TOKEN: '${{ secrets.access-token }}'
