name: 'Set auto merge'
'on':
  workflow_call:
    # secrets:
    #   GITHUB_TOKEN:
    #     required: true

jobs:
  set-auto-merge:
    runs-on: ubuntu-latest
    #if: ${{ github.event.review.state == 'APPROVED' && github.event.review.pull_request.user.login == 'zregvart' }} #dependabot[bot]
    steps:
      - run: gh pr merge ${{ github.event.review.pull_request.issue_url }} --auto
        env:
          GH_REPO: ${{ github.event.review.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
