name: 'Set auto merge'
'on':
  workflow_call:

jobs:
  set-auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.review.state == 'APPROVED' && github.event.pull_request.user.login == 'zregvart' }} #dependabot[bot]
    steps:
      - run: gh pr merge ${{ github.event.pull_request.number }} --merge --auto --delete-branch
        env:
          GH_REPO: ${{ github.event.repository.full_name }}
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
